services:
    api:
        build: 
            context: .
        ports:
            - 8080:8080
        volumes:
            - ./ssl_cert.crt:/code/ssl_cert.crt
            - ./ssl_key.key:/code/ssl_key.key
        restart: unless-stopped
        depends_on:
            - postgres-api
    postgres-api:
        image: postgres:16
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: postgres
        volumes:
            - ./postgres_data:/var/lib/postgresql/data
        restart: unless-stopped
    nginx:
        image: nginx:latest
        ports:
            - 80:80
            - 443:443
        volumes:
            - ./nginx.conf:/etc/nginx/nginx.conf:ro
            - ./html:/usr/share/nginx/html:ro
            - ./ssl_cert.crt:/etc/nginx/ssl/ssl_cert.crt:ro
            - ./ssl_key.key:/etc/nginx/ssl/ssl_key.key:ro
        depends_on:
            - api
        restart: unless-stopped
